ENV["LC_ALL"] = "en_GB.UTF-8"
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |v|
    v.name = "bastion-host"
    v.memory = 2048
    v.cpus = 1
  end
  config.vm.network "private_network", ip: "10.10.0.124"
  config.ssh.forward_agent = true
  config.vm.hostname = "bastion-host"
  config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: ".ssh/authorized_keys"
  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.raw_arguments = "--private-key=~/.ssh/id_rsa"
    ansible.playbook = "ansible/provision.yml"
    ansible.inventory_path = "ansible/hosts"
    ansible.become = true
    ansible.host_key_checking = false
    ansible.limit = "10.10.0.124"
    ansible.groups = {
      "default"   =>  ["10.10.0.124"]
    }
  end
end
